/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sesio3;

public class App {
    public String getGreeting() {
        return "Hello World!";
        Autor autor = new Autor();
        autor.setNombre(nombre:"Panchito");
        autor.setApellido(apellido:"Torres");
        autor.setNombre(edad:"18");
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Libro libro = new Libro();
        libro.setTitulo(Titulo:"Reglas para seducir");
        libro.setAutor(autor);
        libro.setNumeroPaginas(numeroPaginas:30);

        System.out.printl("Libro: "+Libro.getTitulo());
        System.out.printl("Autor: "+Libro.getAutor.getNombre());
        +" "+Libro.getAutor().getApellido();

    }
}
